### ISSUE TITLE
Email headers

### ISSUE THREAD

**Issue by jpagex** [alexgaribay/sendgrid_elixir#20]
The `add_header` function is used to add a custom header for the SendGrid API request but there is no function to add a header to the email as defined in https://sendgrid.com/docs/API_Reference/api_v3.html.

How would you distinguish both?

**Comment by alexgaribay** [comment]
It looks like there's currently a bug with the headers. I'll update the code to include the headers as part of the email object and not as part of the actual request headers.

**Comment by alexgaribay** [comment]
This is fixed now in v1.8 👍
