### ISSUE TITLE
Send email with sandbox: true require api_key

### ISSUE THREAD

**Issue by mbenatti** [alexgaribay/sendgrid_elixir#22]
Hello, 
In my point of view when the mode is in "sandbox", this shouldn't require the "api_key" config.
This error occurs when I send an email with `sandbox: true` option and without api_key(dev or test mode):

```Elixir
     ** (RuntimeError) No API key is configured for SendGrid. Update your config before making an API call.
     
         config :sendgrid,
           api_key: "sengrid_api_key"
```

**Comment by alexgaribay** [comment]
Sandbox isn't defined by me, it's defined by the SendGrid API. It still requires a valid API key to work.

https://sendgrid.com/docs/API_Reference/api_v3.html

This is directly from their docs about enabling the sandbox:

> This allows you to send a test email to ensure that your request body is valid and formatted correctly.

**Comment by mbenatti** [comment]
Any working around or plans to implement a logic avoid the required `api_key` for `:dev` or `:test` when it need to send an email ?
Or the objective of this API is only to follow sendgrid docs?
