### ISSUE TITLE
Upgrade to SendGrid v3 Web API

### ISSUE THREAD

**Issue by thinkingserious** [alexgaribay/sendgrid_elixir#4]
https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/how_to_migrate_from_v2_to_v3_mail_send.html
https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

Thanks!

**Comment by alexgaribay** [comment]
Thanks for the heads up. The new send API looks great and looks way more developer friendly (easier for me to maintain!). And I'm glad there's a sandbox mode 👍!

**Comment by alexgaribay** [comment]
New API committed in v1.0.0 👍
